# .github/workflows/tests.yml
name: Tests

on:
  push:
    branches:
      - '!main'
      - '!release-**'
  pull_request:
  workflow_dispatch:

jobs:
  lint-app:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "duster"
        uses: tighten/duster-action@v3
        with:
          args: lint --using=pint -v

  test-app:
    needs: lint-app
    runs-on: ubuntu-24.04
    services:
      meilisearch:
        image: getmeili/meilisearch:v1.10
        ports:
          - 7700:7700
        env:
          MEILI_MASTER_KEY: masterKey
          MEILI_NO_ANALYTICS: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: xdebug

      - name: Create SQLite Database
        run: |
          touch database/testing.sqlite

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Configure Meilisearch Environment
        run: |
          sed -i 's/^SCOUT_DRIVER=.*/SCOUT_DRIVER=meilisearch/' .env || echo "SCOUT_DRIVER=meilisearch" >> .env
          sed -i 's/^MEILISEARCH_HOST=.*/MEILISEARCH_HOST=http:\/\/localhost:7700/' .env || echo "MEILISEARCH_HOST=http://localhost:7700" >> .env
          sed -i 's/^MEILISEARCH_KEY=.*/MEILISEARCH_KEY=masterKey/' .env || echo "MEILISEARCH_KEY=masterKey" >> .env

      - name: Generate App Key
        run: php artisan key:generate

      - name: Run Tests
        run: php artisan test --parallel

  build-image:
    # needs: [lint-app, test-app]
    needs: [lint-app]
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: production
